version: "3.8"

services:
  sso:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 50051:50051
    networks:
      - sso
  
  postgres:
    image: postgres:17-alpine
    container_name: sso_db
    environment:
      - POSTGRES_DB=${DB_NAME?}
      - POSTGRES_USER=${DB_USER?}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - sso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER?} -d ${DB_NAME?}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  redis:
    image: redis:7-alpine
    container_name: sso_redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - sso

volumes:
  postgres_data:
  redis_data:

networks:
  sso:
    driver: bridge

