grpc: # server
  port: 50051 
  timeout: 5s # 

db: # postgres user here
  user: "dc" 
  password: 123
  host: 127.0.0.1 # localhost
  port: 5432 # default
  name: "sso" 
  sslmode: "disable"

redis: # for caching
  host: 127.0.0.1 # localhost
  port: 6379

jwt: # for proper auth
  secret: ${JWT_SECRET} # env var
  access_token_duration: 3600s # 1 hour
  refresh_token_duration: 2592000s # 30 days
